# Generated by Django 5.0.7 on 2025-10-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('s3_key', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('entities', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='uploaded', max_length=50)),
            ],
        ),
    ]
